use UNIVER
SELECT 
    FACULTY.FACULTY_NAME AS Факультет,
    PULPIT.PULPIT_NAME AS Кафедра,
    GROUPS.PROFESSION AS Специальность,
    SUBJECT.SUBJECT_NAME AS Дисциплина,
    STUDENT.NAME AS Имя_Студента,
    CASE 
        WHEN PROGRESS.NOTE = 6 THEN 'шесть'
        WHEN PROGRESS.NOTE = 7 THEN 'семь'
        WHEN PROGRESS.NOTE = 8 THEN 'восемь'
    END AS Оценка
FROM 
    PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE 
    PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY 
    PROGRESS.NOTE DESC;
