use UNIVER
SELECT 
    PULPIT.PULPIT_NAME AS Кафедра,
    ISNULL(TEACHER.TEACHER_NAME, '***') AS Преподаватель
FROM 
    PULPIT
LEFT OUTER JOIN 
    TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT
ORDER BY 
    PULPIT.PULPIT_NAME DESC;
