
PRINT '@@ROWCOUNT: ' + CAST(@@ROWCOUNT AS VARCHAR);
PRINT '@@VERSION: ' + @@VERSION;
PRINT '@@SPID: ' + CAST(@@SPID AS VARCHAR);
PRINT '@@ERROR: ' + CAST(@@ERROR AS VARCHAR);
PRINT '@@SERVERNAME: ' + ISNULL(@@SERVERNAME, 'NULL');
PRINT '@@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR);
PRINT '@@FETCH_STATUS: ' + CAST(@@FETCH_STATUS AS VARCHAR);
PRINT '@@NESTLEVEL: ' + CAST(@@NESTLEVEL AS VARCHAR);
