SELECT PULPIT_NAME
FROM PULPIT
WHERE FACULTY IN (
    SELECT FACULTY
    FROM PROFESSION
    WHERE PROFESSION_NAME LIKE '%технология%' OR PROFESSION_NAME LIKE '%технологии%'
);

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT
INNER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY
INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
WHERE PROFESSION.PROFESSION_NAME LIKE '%технология%' OR PROFESSION.PROFESSION_NAME LIKE '%технологии%';
