SELECT 
    (SELECT AVG(NOTE) 
     FROM PROGRESS 
     WHERE SUBJECT = 'нюХо') AS AVG_OAiP,
    (SELECT AVG(NOTE) 
     FROM PROGRESS 
     WHERE SUBJECT = 'ад') AS AVG_BD,
    (SELECT AVG(NOTE) 
     FROM PROGRESS 
     WHERE SUBJECT = 'ясад') AS AVG_SUBD;
