SELECT NAME
FROM STUDENT S
WHERE 5 < ALL (
    SELECT P.NOTE
    FROM PROGRESS P
    WHERE P.IDSTUDENT = S.IDSTUDENT
);
SELECT NAME
FROM STUDENT S
WHERE 8 < ANY (
    SELECT P.NOTE
    FROM PROGRESS P
    WHERE P.IDSTUDENT = S.IDSTUDENT
);
